# stremng performance settings
spring.datasource.hikari.maximum-pool-size=15
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=10000
spring.datasource.hikari.validation-timeout=3000

# Background DB persistence concurrency
tracker.background-db-concurrency=2
